"""add name column to devices

Revision ID: 64fe66890fe2
Revises: 696a90b0d0c0
Create Date: 2025-11-19 12:13:42.737637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64fe66890fe2'
down_revision: Union[str, Sequence[str], None] = '696a90b0d0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'name')
    # ### end Alembic commands ###
